Subnet allocations
==================

Subnet assignments in `10/8` subnet (CRXN inter-network)

== Deavmi's subnet allocations ==

****
*IRC:* _deavmi_ on BonoboNET/Freenode

*E-mail:* _deavmi@disroot.org_
****

=== Subnet (A) ===

****
This is my network services subnet where all my servers for
Git, IRC, sshchat, redmine and more live.
****

*Subnet:* `10.0.0.0`

*Subnet mask/prefix:* `255.255.0.0` or `/16`

*Known devices:*

-------------------------------
10.0.0.1 is my Pi router
10.0.0.4 is my home laptop
-------------------------------

=== Subnet (B) ===

****
This is the subnet for my personal devices.
****

*Subnet:* `10.1.0.0`

*Subnet mask/prefix:* `255.255.0.0` or `/16`

*Known devices:*

------------------------------------------
10.1.0.1 is my Pi router
10.1.0.2 is my Pi personal
10.1.0.3 is my Lockdown.BNET IRC server
10.1.0.4 is my laptop
10.1.0.7 is my desktop
10.1.0.11 is my x86 server
10.1.0.12 is my other x86 server
------------------------------------------

=== Subnet (D) ===

****
This subnet is for personal devices in Stellenbosch (as I go to
university there) along with some network services I run from there
too.
****

*Subnet:* `10.4.0.0`

*Subnet mask/prefix:* `255.255.0.0` or `/16`

*Known devices:*

---------------------------------
10.4.0.1 is my Pi router
10.4.0.2 is my University Desktop
10.4.0.3 is my University Laptop
---------------------------------

== Skippy's subnet allocations ==

****
*IRC:* _skippy_ on BonoboNET, _ohmyskippy_ on Freenode
****

=== Subnet (A) ===

****
No description
****

*Subnet:* `10.2.0.0`

*Subnet mask/prefix:* `255.255.0.0` or `/16`

*Known devices:*

---------------
10.2.0.1 router
10.2.0.2 laptop
---------------

== Chris's subnet allocations ==

****
*IRC:* _chris_ on BonoboNET
****

=== Subnet (A) ===

****
No description
****

*Subnet:* `10.5.0.1`

*Subnet mask/prefix:* `255.255.255.255` or `/32`

*Known devices:*

-------------------------------
10.5.0.1 Router for IPv6 NETMAP-NAT
-------------------------------