Network services
================

This page aims at being a one-stop shop for finding available network
services for public use on the CRXN inter-network.

== IRC-related services ==

=== BonoboNET WebIRC ===

An instance of the KiwiIRC web IRC client is available
for users wanting to connect to the BonoboNET IRC
network.

*HTTP Address:* link:http://10.0.0.2:81[]

=== BonoboNET IRC network ===

*BonoboNET* is an IRC network that is available on CRXN,
amongst other networks (cjdns, yggdrasil, clear-net).

So far there are only two BNET nodes available over CRXN:

1. *lockdown.bnet:* `irc://10.1.0.3:6667`
2. *shitpoes.bnet:* `irc://10.1.0.12:6667`
3. TODO: Add Kaotisk's node

More information regarding BonoboNET can be found
link:/projects/bonobonet[here].

== SSHChat ==

SSHChat is a custom ssh server that provides a chat interface rather
than the default, normally a shell, to the user. Anything sent via
this interface appears on the screens of the other users' chat interfaces
and you end up with a chat program that requires only ssh to be installed!

=== Deavmi's sshchat server ===

Deavmi's sshchat server can be accessed via the given parameters:

* *Server address:* `10.0.0.2`
* *Server port:* `2227`

Use it like so:

****
ssh <username>@10.0.0.2 -p 2227
****

Where `<username>` is your screen name.
